detectors:
  IrresponsibleModule:
    enabled: false

directories:
  "db/migrate":
    UncommunicativeVariableName:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
