inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - public/*
    - vendor/**/*
    - lib/tasks/**/*
    - db/schema.rb
    - db/migrate/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
  UseCache: true
  TargetRubyVersion: 3.3.0
  TargetRailsVersion: 7.1.3
  EnabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/Copyright:
  Enabled: false
