#
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= Integer(ENV['SIDEKIQ_CONCURRENCY'] || ENV.fetch('RAILS_MAX_THREADS') { 5 }) + 2 %>
  timeout: <%= ENV.fetch('DB_TIMEOUT', 5_000) %>

development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>

staging:
  <<: *default
  database: <%= ENV['DB_STAGING_NAME'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
