:concurrency: <%= Integer(ENV.fetch('SIDEKIQ_CONCURRENCY') { 5 }) %>
:timeout: <%= Integer(ENV.fetch('SIDEKIQ_TIMEOUT_SECONDS') { 25 }) %>
:queues:
  - [default, 1]
  - [messengers, 1]
  - [busy, 5]
  - [busier, 7]
  - [busiest, 10]
