name: Reek linter

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  reek:
    name: Reek

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 'Gemfile.lock'
          bundler-cache: true

      - name: Run reek linting
        run: bundle exec reek .
