name: Rubocop linter

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  rubocop:
    name: Rubocop

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 'Gemfile.lock'
          bundler-cache: true

      - name: Run rubocop linting
        run: bundle exec rubocop .
